import {
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import type { ServicePerformance } from "@/data/manager/reports";

interface ManagerServiceDistributionChartProps {
  data: ServicePerformance[];
}

export default function ManagerServiceDistributionChart({
  data,
}: ManagerServiceDistributionChartProps) {
  return (
    <div className="rounded-xl border bg-card p-5 shadow-sm">
      {/* Header */}

      <div className="mb-6">
        <h2 className="text-lg font-semibold">
          Service Distribution
        </h2>

        <p className="mt-1 text-sm text-muted-foreground">
          Number of work orders generated by service type.
        </p>
      </div>

      {/* Chart */}

      <div className="h-[320px]">
        {data.length === 0 ? (
          <div className="flex h-full items-center justify-center">
            <p className="text-sm text-muted-foreground">
              No service data available.
            </p>
          </div>
        ) : (
          <ResponsiveContainer
            width="100%"
            height="100%"
          >
            <BarChart
              data={data}
              margin={{
                top: 10,
                right: 20,
                left: 0,
                bottom: 50,
              }}
            >
              <CartesianGrid
                strokeDasharray="3 3"
              />

              <XAxis
                dataKey="service"
                angle={-25}
                textAnchor="end"
                interval={0}
                tick={{ fontSize: 11 }}
              />

              <YAxis
                allowDecimals={false}
                tick={{ fontSize: 12 }}
              />

              <Tooltip />

              <Bar
                dataKey="workOrders"
                name="Work Orders"
                fill="#2563eb"
                radius={[6, 6, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        )}
      </div>
    </div>
  );
}