ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS started_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS sla_due_date TIMESTAMP,
    ADD COLUMN IF NOT EXISTS sla_breached BOOLEAN DEFAULT FALSE;